package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	dirPath := flag.String("dir", ".", "Directory to scan for sandboxed Go interfaces")
	flag.Parse()

	absPath, err := filepath.Abs(*dirPath)
	if err != nil {
		fmt.Printf("Failed to resolve absolute path: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("[gobox-gen] Scanning directory: %s\n", absPath)
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, absPath, nil, parser.ParseComments)
	if err != nil {
		fmt.Printf("Failed to parse Go files: %v\n", err)
		os.Exit(1)
	}

	for _, pkg := range pkgs {
		processPackage(pkg, absPath)
	}
}

type methodSpec struct {
	Name    string
	Params  []paramSpec
	Results []paramSpec
}

type paramSpec struct {
	Name string
	Type string
}

type interfaceSpec struct {
	Name    string
	Methods []methodSpec
}

func processPackage(pkg *ast.Package, absPath string) {
	var sandboxedInterfaces []interfaceSpec
	packageName := pkg.Name

	for _, file := range pkg.Files {
		ast.Inspect(file, func(n ast.Node) bool {
			decl, ok := n.(*ast.GenDecl)
			if !ok || decl.Tok != token.TYPE {
				return true
			}

			isSandboxed := false
			if decl.Doc != nil {
				for _, comment := range decl.Doc.List {
					if strings.Contains(comment.Text, "//gobox:sandbox") {
						isSandboxed = true
						break
					}
				}
			}

			if isSandboxed {
				for _, spec := range decl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					interfaceType, ok := typeSpec.Type.(*ast.InterfaceType)
					if !ok {
						continue
					}
					interfaceName := typeSpec.Name.Name
					
					// AST Validation: Reject embedded interfaces
					valid := true
					for _, field := range interfaceType.Methods.List {
						if len(field.Names) == 0 {
							fmt.Printf("[gobox-gen] ERROR: Interface %s contains an embedded interface. Glassbox currently does not support proxying embedded interfaces.\n", interfaceName)
							valid = false
							break
						}
					}
					if !valid {
						continue
					}
					
					fmt.Printf("[gobox-gen] Found Sandboxed Interface: %s\n", interfaceName)
					
					intfSpec := interfaceSpec{Name: interfaceName}
					for _, field := range interfaceType.Methods.List {
						funcType, ok := field.Type.(*ast.FuncType)
						if !ok {
							continue
						}

						methodName := field.Names[0].Name
						var params []paramSpec
						var results []paramSpec

						// Parse parameters
						if funcType.Params != nil {
							for idx, p := range funcType.Params.List {
								pType := typeExprToString(p.Type)
								if len(p.Names) > 0 {
									for _, name := range p.Names {
										params = append(params, paramSpec{Name: name.Name, Type: pType})
									}
								} else {
									params = append(params, paramSpec{Name: fmt.Sprintf("arg%d", idx), Type: pType})
								}
							}
						}

						// Parse results
						if funcType.Results != nil {
							for idx, r := range funcType.Results.List {
								rType := typeExprToString(r.Type)
								rName := ""
								if len(r.Names) > 0 {
									rName = r.Names[0].Name
								} else {
									rName = fmt.Sprintf("ret%d", idx)
								}
								results = append(results, paramSpec{Name: rName, Type: rType})
							}
						}

						intfSpec.Methods = append(intfSpec.Methods, methodSpec{
							Name:    methodName,
							Params:  params,
							Results: results,
						})
					}
					sandboxedInterfaces = append(sandboxedInterfaces, intfSpec)
				}
			}

			return true
		})
	}

	if len(sandboxedInterfaces) > 0 {
		for _, intf := range sandboxedInterfaces {
			generateProxy(packageName, intf, absPath)
		}
		generateGuest(packageName, sandboxedInterfaces, absPath)
	}
}

func generateProxy(packageName string, intf interfaceSpec, absPath string) {
	interfaceName := intf.Name
	methods := intf.Methods

	// Construct proxy source code
	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("// Code generated by gobox-gen. DO NOT EDIT.\npackage %s\n\n", packageName))
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"github.com/tetratelabs/wazero/api\"\n")
	buf.WriteString("\tgapi \"github.com/glassbox-go/api\"\n")
	buf.WriteString("\tgbridge \"github.com/glassbox-go/binarybridge\"\n")
	buf.WriteString("\tgruntime \"github.com/glassbox-go/runtime\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString(fmt.Sprintf("type %sWasmProxy struct {\n", interfaceName))
	buf.WriteString("\tengine *gruntime.Engine\n")
	buf.WriteString("\tlimits *gapi.SandboxLimits\n")
	buf.WriteString("\tpool   chan api.Module\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("var _ %s = (*%sWasmProxy)(nil)\n\n", interfaceName, interfaceName))

	buf.WriteString(fmt.Sprintf("func New%sWasmProxy(engine *gruntime.Engine, limits *gapi.SandboxLimits) (*%sWasmProxy, error) {\n", interfaceName, interfaceName))
	buf.WriteString("\tif limits == nil {\n")
	buf.WriteString("\t\tlimits = gapi.NewBuilder().Build()\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif engine == nil {\n")
	buf.WriteString("\t\treturn nil, fmt.Errorf(\"engine cannot be nil\")\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\t// Eagerly verify module is compilable/instantiable and initialize the pool\n")
	buf.WriteString("\tctx := context.Background()\n")
	buf.WriteString(fmt.Sprintf("\tmod, err := engine.GetInstance(ctx, \"%s\", limits)\n", packageName)) // Use packageName here!
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString(fmt.Sprintf("\t\treturn nil, gapi.NewSandboxSecurityError(fmt.Sprintf(\"Failed to initialize secure Wasm sandbox for %s: %%v\", err))\n", packageName))
	buf.WriteString("\t}\n")
	
	buf.WriteString("\tif mod.ExportedFunction(\"malloc\") == nil {\n")
	buf.WriteString("\t\tmod.Close(ctx)\n")
	buf.WriteString("\t\treturn nil, gapi.NewSandboxSecurityError(\"wasm module does not export malloc\")\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif mod.ExportedFunction(\"free\") == nil {\n")
	buf.WriteString("\t\tmod.Close(ctx)\n")
	buf.WriteString("\t\treturn nil, gapi.NewSandboxSecurityError(\"wasm module does not export free\")\n")
	buf.WriteString("\t}\n")
	for _, method := range methods {
		buf.WriteString(fmt.Sprintf("\tif mod.ExportedFunction(\"%s\") == nil {\n", method.Name))
		buf.WriteString("\t\tmod.Close(ctx)\n")
		buf.WriteString(fmt.Sprintf("\t\treturn nil, gapi.NewSandboxSecurityError(\"wasm module does not export %s\")\n", method.Name))
		buf.WriteString("\t}\n")
	}

	buf.WriteString("\tmod.Close(ctx)\n\n")

	buf.WriteString(fmt.Sprintf("\tp := &%sWasmProxy{\n", interfaceName))
	buf.WriteString("\t\tengine: engine,\n")
	buf.WriteString("\t\tlimits: limits,\n")
	buf.WriteString("\t\tpool:   make(chan api.Module, 10), // Buffered pool for reuse\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn p, nil\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("func (p *%sWasmProxy) Close() error {\n", interfaceName))
	buf.WriteString("\tctx := context.Background()\n")
	buf.WriteString("\tfor {\n")
	buf.WriteString("\t\tselect {\n")
	buf.WriteString("\t\tcase mod := <-p.pool:\n")
	buf.WriteString("\t\t\tmod.Close(ctx)\n")
	buf.WriteString("\t\tdefault:\n")
	buf.WriteString("\t\t\treturn nil\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("func (p *%sWasmProxy) acquireModule(ctx context.Context) (api.Module, error) {\n", interfaceName))
	buf.WriteString("\tselect {\n")
	buf.WriteString("\tcase mod := <-p.pool:\n")
	buf.WriteString("\t\treturn mod, nil\n")
	buf.WriteString("\tdefault:\n")
	buf.WriteString(fmt.Sprintf("\t\treturn p.engine.GetInstance(ctx, \"%s\", p.limits)\n", packageName))
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("func (p *%sWasmProxy) releaseModule(mod api.Module) {\n", interfaceName))
	buf.WriteString("\tselect {\n")
	buf.WriteString("\tcase p.pool <- mod:\n")
	buf.WriteString("\tdefault:\n")
	buf.WriteString("\t\tmod.Close(context.Background())\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	// Write method implementations
	for _, method := range methods {
		paramList := []string{}
		for _, p := range method.Params {
			paramList = append(paramList, fmt.Sprintf("%s %s", p.Name, p.Type))
		}

		resultTypes := []string{}
		for _, r := range method.Results {
			resultTypes = append(resultTypes, r.Type)
		}

		retString := strings.Join(resultTypes, ", ")
		if len(resultTypes) > 1 {
			retString = "(" + retString + ")"
		}

		buf.WriteString(fmt.Sprintf("func (p *%sWasmProxy) %s(%s) %s {\n", interfaceName, method.Name, strings.Join(paramList, ", "), retString))
		buf.WriteString("\t// 1. Establish Context limits boundary\n")
		hasCtxParam := false
		for _, p := range method.Params {
			if p.Name == "ctx" || p.Type == "context.Context" {
				hasCtxParam = true
				break
			}
		}
		if !hasCtxParam {
			buf.WriteString("\tctx := context.Background()\n")
		}
		buf.WriteString("\tif p.limits.Timeout() > 0 {\n")
		buf.WriteString("\t\tvar cancel context.CancelFunc\n")
		buf.WriteString("\t\tctx, cancel = context.WithTimeout(ctx, p.limits.Timeout())\n")
		buf.WriteString("\t\tdefer cancel()\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\tif len(p.limits.AllowedDirectories()) > 0 || len(p.limits.AllowedNetworkAddresses()) > 0 {\n")
		buf.WriteString("\t\tctx = gapi.WithActiveLimits(ctx, p.limits)\n")
		buf.WriteString("\t}\n\n")

		for _, p := range method.Params {
			if p.Name == "path" || p.Name == "filePath" {
				buf.WriteString("\tgate := &gapi.SecurityGate{}\n")
				buf.WriteString(fmt.Sprintf("\tif err := gate.CheckFileAccess(ctx, %s); err != nil {\n", p.Name))
				buf.WriteString(fmt.Sprintf("\t\treturn %s\n", generateZeroReturns(method.Results, "err")))
				buf.WriteString("\t}\n\n")
			}
		}

		buf.WriteString("\tvar payload []byte\n")
		buf.WriteString("\tvar err error\n")
		buf.WriteString("\tpayload, err = gbridge.SerializeAsBytes([]interface{}{\n")
		for _, p := range method.Params {
			if p.Type == "context.Context" || p.Type == "Context" {
				continue
			}
			buf.WriteString(fmt.Sprintf("\t\t\t%s,\n", p.Name))
		}
		buf.WriteString("\t\t})\n")
		buf.WriteString("\t\tif err != nil {\n")
		buf.WriteString(fmt.Sprintf("\t\t\treturn %s\n", generateZeroReturns(method.Results, "fmt.Errorf(\"serialization failed: %w\", err)")))
		buf.WriteString("\t\t}\n\n")

		buf.WriteString("\t\t// Get a module from the pool\n")
		buf.WriteString("\t\tmod, err := p.acquireModule(ctx)\n")
		buf.WriteString("\t\tif err != nil {\n")
		buf.WriteString(fmt.Sprintf("\t\t\treturn %s\n", generateZeroReturns(method.Results, "fmt.Errorf(\"failed to get sandbox instance: %w\", err)")))
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t\tdefer p.releaseModule(mod)\n\n")

		buf.WriteString("\t\tmalloc := mod.ExportedFunction(\"malloc\")\n")
		buf.WriteString("\t\tif malloc == nil {\n")
		buf.WriteString(fmt.Sprintf("\t\t\treturn %s\n", generateZeroReturns(method.Results, "fmt.Errorf(\"wasm module does not export malloc\")")))
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t\tfree := mod.ExportedFunction(\"free\")\n")
		buf.WriteString("\t\tif free == nil {\n")
		buf.WriteString(fmt.Sprintf("\t\t\treturn %s\n", generateZeroReturns(method.Results, "fmt.Errorf(\"wasm module does not export free\")")))
		buf.WriteString("\t\t}\n")
		buf.WriteString(fmt.Sprintf("\t\twasmFunc := mod.ExportedFunction(\"%s\")\n", method.Name))
		buf.WriteString("\t\tif wasmFunc == nil {\n")
		buf.WriteString(fmt.Sprintf("\t\t\treturn %s\n", generateZeroReturns(method.Results, fmt.Sprintf("fmt.Errorf(\"wasm module does not export %%s\", %q)", method.Name))))
		buf.WriteString("\t\t}\n\n")

		buf.WriteString("\t\tresults, err := malloc.Call(ctx, uint64(len(payload)))\n")
		buf.WriteString("\t\tif err != nil {\n")
		buf.WriteString(fmt.Sprintf("\t\t\treturn %s\n", generateZeroReturns(method.Results, "fmt.Errorf(\"failed to allocate guest memory: %w\", err)")))
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t\tguestPtr := uint32(results[0])\n")
		buf.WriteString("\t\tif !mod.Memory().Write(guestPtr, payload) {\n")
		buf.WriteString(fmt.Sprintf("\t\t\treturn %s\n", generateZeroReturns(method.Results, "fmt.Errorf(\"failed to write payload to guest memory\")")))
		buf.WriteString("\t\t}\n\n")

		buf.WriteString("\t\t// Execute guest function and release temporary scratch buffer\n")
		buf.WriteString("\t\tcallRes, err := wasmFunc.Call(ctx, uint64(guestPtr), uint64(len(payload)))\n")
		buf.WriteString("\t\t_, _ = free.Call(ctx, uint64(guestPtr))\n")
		buf.WriteString("\t\tif err != nil {\n")
		buf.WriteString(fmt.Sprintf("\t\t\treturn %s\n", generateZeroReturns(method.Results, "fmt.Errorf(\"sandbox execution failed: %w\", err)")))
		buf.WriteString("\t\t}\n\n")

		buf.WriteString("\t\tretPtr := uint32(callRes[0] >> 32)\n")
		buf.WriteString("\t\tretLen := uint32(callRes[0] & 0xFFFFFFFF)\n")
		buf.WriteString("\t\tretBytes, ok := mod.Memory().Read(retPtr, retLen)\n")
		buf.WriteString("\t\tif !ok {\n")
		buf.WriteString(fmt.Sprintf("\t\t\treturn %s\n", generateZeroReturns(method.Results, "fmt.Errorf(\"failed to read return payload from guest memory\")")))
		buf.WriteString("\t\t}\n\n")

		if len(method.Results) > 0 {
			buf.WriteString("\t\t// Use a local struct for direct deserialization to fix struct type assertion bug\n")
			buf.WriteString("\t\tvar outResults struct {\n")
			for idx, r := range method.Results {
				buf.WriteString(fmt.Sprintf("\t\t\tRet%d %s\n", idx, r.Type))
			}
			buf.WriteString("\t\t}\n")
			buf.WriteString("\t\terr = gbridge.DeserializeFromBytes(retBytes, &outResults)\n")
			buf.WriteString("\t\tif err != nil {\n")
			buf.WriteString(fmt.Sprintf("\t\t\treturn %s\n", generateZeroReturns(method.Results, "fmt.Errorf(\"deserialization failed: %w\", err)")))
			buf.WriteString("\t\t}\n\n")
			buf.WriteString("\t\t_, _ = free.Call(ctx, uint64(retPtr))\n\n")
			var rets []string
			for idx, r := range method.Results {
				if r.Type == "error" {
					rets = append(rets, fmt.Sprintf("gbridge.UnmarshalError(outResults.Ret%d)", idx))
				} else {
					rets = append(rets, fmt.Sprintf("outResults.Ret%d", idx))
				}
			}
			buf.WriteString(fmt.Sprintf("\t\treturn %s\n", strings.Join(rets, ", ")))
		} else {
			buf.WriteString("\t\t_, _ = free.Call(ctx, uint64(retPtr))\n")
		}
		buf.WriteString("}\n\n")
	}

	outputPath := filepath.Join(absPath, fmt.Sprintf("%s_proxy.go", strings.ToLower(interfaceName)))
	
	// Format the source code before writing
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Printf("Failed to format generated proxy file: %v\n", err)
		// Fallback to unformatted if formatting fails
		formatted = buf.Bytes()
	}

	err = os.WriteFile(outputPath, formatted, 0644)
	if err != nil {
		fmt.Printf("Failed to write generated proxy file: %v\n", err)
	} else {
		fmt.Printf("[gobox-gen] Successfully generated proxy: %s\n", outputPath)
	}
}

func generateGuest(packageName string, interfaces []interfaceSpec, absPath string) {
	guestDir := filepath.Join(absPath, "guest")
	if err := os.MkdirAll(guestDir, 0755); err != nil {
		fmt.Printf("Failed to create guest directory: %v\n", err)
		return
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by gobox-gen. DO NOT EDIT.\n")
	buf.WriteString("package main\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"unsafe\"\n")
	buf.WriteString("\t\"github.com/glassbox-go/binarybridge\"\n")
	
	pkgPath := "github.com/glassbox-go/" + filepath.Base(absPath)
	buf.WriteString(fmt.Sprintf("\t\"%s\"\n", pkgPath))
	buf.WriteString(")\n\n")

	buf.WriteString("func main() {}\n\n")
	buf.WriteString("var allocations = make(map[uintptr][]byte)\n\n")
	
	buf.WriteString("//go:wasmexport malloc\n")
	buf.WriteString("func malloc(size uint32) *byte {\n")
	buf.WriteString("\tbuf := make([]byte, size)\n")
	buf.WriteString("\tptr := &buf[0]\n")
	buf.WriteString("\tallocations[uintptr(unsafe.Pointer(ptr))] = buf\n")
	buf.WriteString("\treturn ptr\n")
	buf.WriteString("}\n\n")

	buf.WriteString("//go:wasmexport free\n")
	buf.WriteString("func free(ptr *byte) {\n")
	buf.WriteString("\tdelete(allocations, uintptr(unsafe.Pointer(ptr)))\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func keepAliveAndPack(buf []byte) uint64 {\n")
	buf.WriteString("\tptr := &buf[0]\n")
	buf.WriteString("\tallocations[uintptr(unsafe.Pointer(ptr))] = buf\n")
	buf.WriteString("\treturn (uint64(uint32(uintptr(unsafe.Pointer(ptr)))) << 32) | uint64(len(buf))\n")
	buf.WriteString("}\n\n")

	for _, intf := range interfaces {
		buf.WriteString(fmt.Sprintf("// --- %s ---\n", intf.Name))
		buf.WriteString(fmt.Sprintf("var %sImpl = &%s.%sImpl{}\n\n", strings.ToLower(intf.Name), packageName, intf.Name))

		for _, method := range intf.Methods {
			buf.WriteString(fmt.Sprintf("//go:wasmexport %s\n", method.Name))
			buf.WriteString(fmt.Sprintf("func %s(ptr *byte, size uint32) uint64 {\n", method.Name))
			buf.WriteString("\tpayload := unsafe.Slice(ptr, size)\n")
			buf.WriteString("\tvar args []interface{}\n")
			buf.WriteString("\t_ = binarybridge.DeserializeFromBytes(payload, &args)\n\n")

			var callArgs []string
			argIdx := 0
			for _, p := range method.Params {
				if p.Type == "context.Context" || p.Type == "Context" {
					callArgs = append(callArgs, "context.Background()")
				} else {
					buf.WriteString(fmt.Sprintf("\tvar arg%d %s\n", argIdx, p.Type))
					buf.WriteString(fmt.Sprintf("\tif len(args) > %d {\n", argIdx))
					// Basic type assertion
					buf.WriteString(fmt.Sprintf("\t\tif val, ok := args[%d].(%s); ok {\n", argIdx, p.Type))
					buf.WriteString(fmt.Sprintf("\t\t\targ%d = val\n", argIdx))
					buf.WriteString("\t\t}\n")
					buf.WriteString("\t}\n")
					callArgs = append(callArgs, fmt.Sprintf("arg%d", argIdx))
					argIdx++
				}
			}

			// Do the call
			var retVars []string
			hasError := false
			for i, r := range method.Results {
				if r.Type == "error" {
					hasError = true
					retVars = append(retVars, "err")
				} else {
					retVars = append(retVars, fmt.Sprintf("ret%d", i))
				}
			}

			callStr := ""
			if len(retVars) > 0 {
				callStr = strings.Join(retVars, ", ") + " := "
			}
			callStr += fmt.Sprintf("%sImpl.%s(%s)\n", strings.ToLower(intf.Name), method.Name, strings.Join(callArgs, ", "))
			buf.WriteString("\t" + callStr)

			var serializeArgs []string
			if hasError {
				buf.WriteString("\tvar errOut string\n")
				buf.WriteString("\tif err != nil {\n")
				buf.WriteString("\t\terrOut = err.Error()\n")
				buf.WriteString("\t}\n")
			}

			for i, r := range method.Results {
				if r.Type == "error" {
					serializeArgs = append(serializeArgs, "errOut")
				} else {
					serializeArgs = append(serializeArgs, fmt.Sprintf("ret%d", i))
				}
			}

			buf.WriteString("\tretBytes, _ := binarybridge.SerializeAsBytes([]interface{}{\n")
			for _, sa := range serializeArgs {
				buf.WriteString(fmt.Sprintf("\t\t%s,\n", sa))
			}
			buf.WriteString("\t})\n\n")

			buf.WriteString("\treturn keepAliveAndPack(retBytes)\n")
			buf.WriteString("}\n\n")
		}
	}

	outputPath := filepath.Join(guestDir, "main.go")
	
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Printf("Failed to format generated guest file: %v\n", err)
		formatted = buf.Bytes()
	}

	err = os.WriteFile(outputPath, formatted, 0644)
	if err != nil {
		fmt.Printf("Failed to write generated guest file: %v\n", err)
	} else {
		fmt.Printf("[gobox-gen] Successfully generated guest shim: %s\n", outputPath)
	}
}

func generateZeroReturns(results []paramSpec, lastErr string) string {
	var rets []string
	for i := 0; i < len(results)-1; i++ {
		rets = append(rets, getZeroValue(results[i].Type))
	}
	rets = append(rets, lastErr)
	return strings.Join(rets, ", ")
}

func getZeroValue(t string) string {
	if strings.HasPrefix(t, "map[") {
		return "nil"
	}
	if strings.HasPrefix(t, "[]") {
		return "nil"
	}
	switch t {
	case "string":
		return "\"\""
	case "int", "int32", "int64", "uint32", "uint64", "float32", "float64":
		return "0"
	case "bool":
		return "false"
	default:
		return "nil"
	}
}

func typeExprToString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.ArrayType:
		return "[]" + typeExprToString(t.Elt)
	case *ast.SelectorExpr:
		return typeExprToString(t.X) + "." + t.Sel.Name
	case *ast.StarExpr:
		return "*" + typeExprToString(t.X)
	case *ast.MapType:
		return "map[" + typeExprToString(t.Key) + "]" + typeExprToString(t.Value)
	case *ast.InterfaceType:
		return "interface{}"
	default:
		return fmt.Sprintf("%T", expr)
	}
}
