// Code generated by gobox-gen. DO NOT EDIT.
package main

import (
	"context"
	"github.com/glassbox-go/binarybridge"
	"github.com/glassbox-go/demo"
	"unsafe"
)

func main() {}

var allocations = make(map[uintptr][]byte)

//go:wasmexport malloc
func malloc(size uint32) *byte {
	buf := make([]byte, size)
	ptr := &buf[0]
	allocations[uintptr(unsafe.Pointer(ptr))] = buf
	return ptr
}

//go:wasmexport free
func free(ptr *byte) {
	delete(allocations, uintptr(unsafe.Pointer(ptr)))
}

func keepAliveAndPack(buf []byte) uint64 {
	ptr := &buf[0]
	allocations[uintptr(unsafe.Pointer(ptr))] = buf
	return (uint64(uint32(uintptr(unsafe.Pointer(ptr)))) << 32) | uint64(len(buf))
}

// --- PDFProcessor ---
var pdfprocessorImpl = &demo.PDFProcessorImpl{}

//go:wasmexport ExtractTextFromFile
func ExtractTextFromFile(ptr *byte, size uint32) uint64 {
	payload := unsafe.Slice(ptr, size)
	var args []interface{}
	_ = binarybridge.DeserializeFromBytes(payload, &args)

	var arg0 string
	if len(args) > 0 {
		if val, ok := args[0].(string); ok {
			arg0 = val
		}
	}
	ret0, err := pdfprocessorImpl.ExtractTextFromFile(context.Background(), arg0)
	var errOut string
	if err != nil {
		errOut = err.Error()
	}
	retBytes, _ := binarybridge.SerializeAsBytes([]interface{}{
		ret0,
		errOut,
	})

	return keepAliveAndPack(retBytes)
}

// --- YAMLParser ---
var yamlparserImpl = &demo.YAMLParserImpl{}

//go:wasmexport Parse
func Parse(ptr *byte, size uint32) uint64 {
	payload := unsafe.Slice(ptr, size)
	var args []interface{}
	_ = binarybridge.DeserializeFromBytes(payload, &args)

	var arg0 []byte
	if len(args) > 0 {
		if val, ok := args[0].([]byte); ok {
			arg0 = val
		}
	}
	ret0, err := yamlparserImpl.Parse(context.Background(), arg0)
	var errOut string
	if err != nil {
		errOut = err.Error()
	}
	retBytes, _ := binarybridge.SerializeAsBytes([]interface{}{
		ret0,
		errOut,
	})

	return keepAliveAndPack(retBytes)
}

// --- MarkdownParser ---
var markdownparserImpl = &demo.MarkdownParserImpl{}

//go:wasmexport Render
func Render(ptr *byte, size uint32) uint64 {
	payload := unsafe.Slice(ptr, size)
	var args []interface{}
	_ = binarybridge.DeserializeFromBytes(payload, &args)

	var arg0 []byte
	if len(args) > 0 {
		if val, ok := args[0].([]byte); ok {
			arg0 = val
		}
	}
	ret0, err := markdownparserImpl.Render(context.Background(), arg0)
	var errOut string
	if err != nil {
		errOut = err.Error()
	}
	retBytes, _ := binarybridge.SerializeAsBytes([]interface{}{
		ret0,
		errOut,
	})

	return keepAliveAndPack(retBytes)
}
